language: php

sudo: false

matrix:
    include:
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: 7.2
        - php: 7.3
    fast_finish: true

before_script: composer install
script: composer phpunit
